-- MySQL Script generated by MySQL Workbench
-- Wed Apr 13 17:35:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mokkilaiset
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mokkilaiset
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mokkilaiset` DEFAULT CHARACTER SET utf8 ;
USE `mokkilaiset` ;

-- -----------------------------------------------------
-- Table `mokkilaiset`.`posti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mokkilaiset`.`posti` ;

CREATE TABLE IF NOT EXISTS `mokkilaiset`.`posti` (
  `postinro` CHAR(5) NOT NULL,
  `toimipaikka` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`postinro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mokkilaiset`.`asiakas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mokkilaiset`.`asiakas` ;

CREATE TABLE IF NOT EXISTS `mokkilaiset`.`asiakas` (
  `asiakas_id` INT NOT NULL AUTO_INCREMENT,
  `postinro` CHAR(5) NULL,
  `etunimi` VARCHAR(20) NOT NULL,
  `sukunimi` VARCHAR(40) NOT NULL,
  `lahiosoite` VARCHAR(40) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `puhelinnro` VARCHAR(15) NOT NULL,
  `postituslista` TINYINT NOT NULL,
  PRIMARY KEY (`asiakas_id`),
  CONSTRAINT `postinro_as`
    FOREIGN KEY (`postinro`)
    REFERENCES `mokkilaiset`.`posti` (`postinro`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `postinro_idx` ON `mokkilaiset`.`asiakas` (`postinro` ASC);


-- -----------------------------------------------------
-- Table `mokkilaiset`.`alue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mokkilaiset`.`alue` ;

CREATE TABLE IF NOT EXISTS `mokkilaiset`.`alue` (
  `alue_id` INT NOT NULL AUTO_INCREMENT,
  `nimi` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`alue_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mokkilaiset`.`mokki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mokkilaiset`.`mokki` ;

CREATE TABLE IF NOT EXISTS `mokkilaiset`.`mokki` (
  `mokki_id` INT NOT NULL AUTO_INCREMENT,
  `alue_id` INT NULL,
  `postinro` CHAR(5) NULL,
  `mokkinimi` VARCHAR(45) NOT NULL,
  `katuosoite` VARCHAR(45) NOT NULL,
  `hinta` DOUBLE(8,2) NOT NULL,
  `kuvaus` VARCHAR(150) NOT NULL,
  `henkilomaara` INT NOT NULL,
  `varustelu` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`mokki_id`),
  CONSTRAINT `alue_id_mo`
    FOREIGN KEY (`alue_id`)
    REFERENCES `mokkilaiset`.`alue` (`alue_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `postinro_mo`
    FOREIGN KEY (`postinro`)
    REFERENCES `mokkilaiset`.`posti` (`postinro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `alue_id_idx` ON `mokkilaiset`.`mokki` (`alue_id` ASC);

CREATE INDEX `postinro_idx` ON `mokkilaiset`.`mokki` (`postinro` ASC);


-- -----------------------------------------------------
-- Table `mokkilaiset`.`varaus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mokkilaiset`.`varaus` ;

CREATE TABLE IF NOT EXISTS `mokkilaiset`.`varaus` (
  `varaus_id` INT NOT NULL AUTO_INCREMENT,
  `asiakas_id` INT NULL,
  `mokki_id` INT NULL,
  `varattu_pvm` DATETIME NOT NULL,
  `vahvistus_pvm` DATETIME NULL,
  `varattu_alkupvm` DATETIME NOT NULL,
  `varattu_loppupvm` DATETIME NOT NULL,
  PRIMARY KEY (`varaus_id`),
  CONSTRAINT `asiakas_id_va`
    FOREIGN KEY (`asiakas_id`)
    REFERENCES `mokkilaiset`.`asiakas` (`asiakas_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `mokki_id_va`
    FOREIGN KEY (`mokki_id`)
    REFERENCES `mokkilaiset`.`mokki` (`mokki_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `asiakas_id_idx` ON `mokkilaiset`.`varaus` (`asiakas_id` ASC);

CREATE INDEX `mokki_id_idx` ON `mokkilaiset`.`varaus` (`mokki_id` ASC);


-- -----------------------------------------------------
-- Table `mokkilaiset`.`lasku`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mokkilaiset`.`lasku` ;

CREATE TABLE IF NOT EXISTS `mokkilaiset`.`lasku` (
  `lasku_id` INT NOT NULL AUTO_INCREMENT,
  `varaus_id` INT NULL,
  `summa` DOUBLE(8,2) NOT NULL,
  `alv` DOUBLE(8,2) NOT NULL,
  `maksettu` BIT NOT NULL,
  `erapaiva` DATE NOT NULL,
  `laskupaiva` DATE NULL,
  `laskutyyppi` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`lasku_id`),
  CONSTRAINT `varaus_id_la`
    FOREIGN KEY (`varaus_id`)
    REFERENCES `mokkilaiset`.`varaus` (`varaus_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `varaus_id_idx` ON `mokkilaiset`.`lasku` (`varaus_id` ASC);


-- -----------------------------------------------------
-- Table `mokkilaiset`.`palvelu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mokkilaiset`.`palvelu` ;

CREATE TABLE IF NOT EXISTS `mokkilaiset`.`palvelu` (
  `palvelu_id` INT NOT NULL AUTO_INCREMENT,
  `alue_id` INT NULL,
  `nimi` VARCHAR(40) NOT NULL,
  `tyyppi` VARCHAR(25) NOT NULL,
  `kuvaus` VARCHAR(225) NOT NULL,
  `hinta` DOUBLE(8,2) NOT NULL,
  `alv` DOUBLE(8,2) NOT NULL,
  PRIMARY KEY (`palvelu_id`),
  CONSTRAINT `alue_id_pa`
    FOREIGN KEY (`alue_id`)
    REFERENCES `mokkilaiset`.`alue` (`alue_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `alue_id_idx` ON `mokkilaiset`.`palvelu` (`alue_id` ASC);


-- -----------------------------------------------------
-- Table `mokkilaiset`.`varauksen_palvelut`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mokkilaiset`.`varauksen_palvelut` ;

CREATE TABLE IF NOT EXISTS `mokkilaiset`.`varauksen_palvelut` (
  `varaus_id` INT NULL,
  `palvelu_id` INT NULL,
  `lkm` INT NOT NULL,
  CONSTRAINT `varaus_id_vp`
    FOREIGN KEY (`varaus_id`)
    REFERENCES `mokkilaiset`.`varaus` (`varaus_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `palvelu_id_vp`
    FOREIGN KEY (`palvelu_id`)
    REFERENCES `mokkilaiset`.`palvelu` (`palvelu_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `varaus_id_idx` ON `mokkilaiset`.`varauksen_palvelut` (`varaus_id` ASC);

CREATE INDEX `palvelu_id_idx` ON `mokkilaiset`.`varauksen_palvelut` (`palvelu_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
